import React from "react";
import jsPDF from "jspdf";
import html2canvas from "html2canvas";
import CustomTable from "../../components/table/CustomTable";
import companyLogo from "../../assets/100.png"; // Adjust your logo path

const earnings = [
  { name: "BASIC", amount: 295500.39 },
  { name: "INCR AMOUNT", amount: 27939.86 },
  { name: "BASIC2", amount: 22747.44 },
  { name: "FDA", amount: 39547.91 },
  { name: "VDA", amount: 1472805.68 },
  { name: "COMPLEMENT", amount: 0.0 },
  { name: "H R ALLO", amount: 72480.0 },
  { name: "S.WEIGHTAGE", amount: 31414.16 },
  { name: "Gross Earning", amount: 1962435.44 }
];

const deductions = [
  { name: "PF Contribution", amount: 226798.0 },
  { name: "ESI Contribution", amount: 12578.0 },
  { name: "VISHU ADVANCE", amount: 0.0 },
  { name: "MWF TOUR OTHERS", amount: 0.0 },
  { name: "ONAM ADVANCE", amount: 0.0 },
  { name: "PTAX", amount: 60300.0 },
  { name: "CITU", amount: 0.0 },
  { name: "INTUC", amount: 0.0 },
  { name: "CITU", amount: 0.0 },
  { name: "RNDOFF", amount: -11.56 },
  { name: "Total Deduction", amount: 299664.44 }
];

const AllAbstract = () => {
  const downloadPDF = () => {
    const input = document.getElementById("abstract-section");

    html2canvas(input, { scale: 2 }).then((canvas) => {
      const imgData = canvas.toDataURL("image/png");
      const pdf = new jsPDF("p", "mm", "a4");
      const pageWidth = pdf.internal.pageSize.getWidth();
      const pageHeight = pdf.internal.pageSize.getHeight();
      const imgProps = pdf.getImageProperties(imgData);
      const imgHeight = (imgProps.height * pageWidth) / imgProps.width;

      // Logo
      const logoWidth = 30;
      const logoHeight = 30;
      pdf.addImage(companyLogo, "PNG", 10, 10, logoWidth, logoHeight);

      // Title
      pdf.setFontSize(16);
      pdf.text("Company Name", pageWidth / 2, 20, { align: "center" });
      pdf.setFontSize(14);
      pdf.text("WAGES ABSTRACT - February 2025", pageWidth / 2, 30, { align: "center" });

      // Content Image
      pdf.addImage(imgData, "PNG", 10, 40, pageWidth - 20, imgHeight);

      // Footer
      pdf.setFontSize(10);
      pdf.text("Generated by HR System | Page 1", pageWidth / 2, pageHeight - 10, {
        align: "center"
      });

      pdf.save("wages-abstract.pdf");
    });
  };

  const earningColumns = [
    { name: "EARNING NAME", selector: (row) => row.name },
    { name: "AMOUNT", selector: (row) => row.amount.toFixed(2), right: true }
  ];

  const deductionColumns = [
    { name: "DEDUCTION NAME", selector: (row) => row.name },
    { name: "AMOUNT", selector: (row) => row.amount.toFixed(2), right: true }
  ];

  return (
    <div className="p-6">
      {/* Heading */}
      <div className="flex justify-between mb-4 items-center">
        <h2 className="text-xl font-bold">WAGES ABSTRACT FOR February - 2025</h2>
        <button
          onClick={downloadPDF}
          className="bg-blue-600 text-white px-4 py-2 rounded-md"
        >
          Download PDF
        </button>
      </div>

      {/* Abstract Section */}
      <div id="abstract-section" className="border p-4 rounded-xl shadow">
        <div className="row">
          {/* Earnings */}
          <div className="col-md-6">
            <h3 className="text-lg font-semibold mb-2">EARNINGS</h3>
            <CustomTable
              columns={earningColumns}
              data={earnings}
              showActions={false}
              showSearchBar={false}
              pagination={false}
            />
          </div>

          {/* Deductions */}
          <div className="col-md-6">
            <h3 className="text-lg font-semibold mb-2">DEDUCTIONS</h3>
            <CustomTable
              columns={deductionColumns}
              data={deductions}
              showActions={false}
              showSearchBar={false}
              pagination={false}
            />
          </div>
        </div>
      </div>

      {/* Net Pay */}
      <div className="mt-6 text-right font-semibold text-lg">
        Net Pay: ₹{" "}
        {(
          earnings[earnings.length - 1].amount - deductions[deductions.length - 1].amount
        ).toLocaleString(undefined, { minimumFractionDigits: 2 })}
      </div>
    </div>
  );
};

export default AllAbstract;
