-- AlterTable
ALTER TABLE "Deduction" ALTER COLUMN "amount" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "installment_amt" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "interest" SET DATA TYPE DOUBLE PRECISION;
